### ISSUE TITLE
Provide metadata for artifacthub integration

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn-sandbox/artifacthub#1]
As discussed in https://github.com/keptn/keptn/issues/3406 we want to provide a hub for Keptn integrations directly in the Keptn's bridge and on the Keptn website, instead of having them only listed on Github or maintained in markdown on the website.

Therefore, we want to leverage the ArtifactHub to be able to list all Keptn integrations. A very simple example is [shown here](https://jsfiddle.net/0cwgz647/).

To list the integrations on the artifact hub, metadata has to be provided. For the Keptn integrations, we want to follow a monorepo approach with each Keptn service/integration in a separate folder holding its metadata file.

## Structure of the repo
- The structure that is needed is described here https://staging.artifacthub.io/docs/topics/repositories/#keptn-integrations-repositories 

## Structure of the metadata files
- The structure of a package metadata file is described here https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-pkg.yml 
- An example how a Keptn integration can be described can be found here: https://github.com/tegioz/prometheus-service/blob/master/artifacthub-pkg.yml 

## Action items:
- [x] Define the list of integrations that should be included in the artifact hub
  From Keptn contrib
  - [x] Dynatrace Service
  - [x] Prometheus Service
  - [x] Unleash Service
  - [x] Argo Service
  - [x] Neoload Service
  - [x] Notification Service (mark as deprecated)
  - [x] ServiceNow Service

  from Keptn sandbox
  - [x]  Monaco Service
  - [x] Slack Service
  - [x] Locust Service
  - [x] Job Executor Service
  - [x] Jira Service
  - [x] Artillery Service
  - [x] Litmus Service
  - [x] Grafana Service
  - [x] OneChart Service

- [x] Create metadata files ([example](https://github.com/tegioz/prometheus-service/blob/master/artifacthub-pkg.yml)) for each integration that should be included (see list above)
- [x] #6
- [x] Define widget/overview page to list the integrations ([first draft](https://github.com/keptn/keptn.github.io/issues/892))
- [x] Include overview on Keptn.sh ([first draft](https://github.com/keptn/keptn.github.io/issues/892)) [Preview](https://deploy-preview-893--keptn.netlify.app/docs/integrations/)
- [ ] Include overview in Keptn's bridge -> will be handled in keptn/keptn: https://github.com/keptn/keptn/issues/5830

**Important for Keptn core**
- [ ] Add Keptn logo to helm charts -> will be handled in keptn/keptn: https://github.com/keptn/keptn/issues/5530
- [x] Make Keptn a verified publisher

**Comment by jetzlstorfer** [comment]
Related to https://github.com/keptn-sandbox/job-executor-service/issues/58

**Comment by jetzlstorfer** [comment]
The current draft of integrations in the Keptn documentation: https://deploy-preview-893--keptn.netlify.app/docs/integrations/

**Comment by tegioz** [comment]
Hi @TannerGilbert 

This is Sergio, from Artifact Hub 👋 We'll push a fix for the inline code rendering issue today, thanks!

**Comment by tegioz** [comment]
Fix deployed to staging!

**Comment by TannerGilbert** [comment]
I just checked, and it seems to work as expected now. @tegioz, thanks a lot for fixing this so quickly.

**Comment by tegioz** [comment]
Awesome, no worries 👍

**Comment by christian-kreuzberger-dtx** [comment]
Closing this now.
The two remaining issues are
* https://github.com/keptn/keptn/issues/5830
* https://github.com/keptn/keptn/issues/5530

and need to be handled in Keptn Core.

Thanks everyone for the help!
